package customError

import "errors"

var (
	BadRequestError            = errors.New("Bad request")
	ErrBadRequest              = errors.New("Bad request")
	WrongCredentialsError      = errors.New("Wrong Credentials")
	ErrWrongCredentials        = errors.New("Wrong Credentials")
	NotFoundError              = errors.New("Not Found")
	ErrNotFound                = errors.New("Not Found")
	UnauthorizedError          = errors.New("Unauthorized")
	ErrUnauthorized            = errors.New("Unauthorized")
	ForbiddenError             = errors.New("Forbidden")
	ErrForbidden               = errors.New("Forbidden")
	PermissionDeniedError      = errors.New("Permission Denied")
	ErrPermissionDenied        = errors.New("Permission Denied")
	ExpiredCSRFError           = errors.New("Expired CSRF token")
	ErrExpiredCSRF             = errors.New("Expired CSRF token")
	WrongCSRFTokenError        = errors.New("Wrong CSRF token")
	ErrWrongCSRFToken          = errors.New("Wrong CSRF token")
	CSRFNotPresentedError      = errors.New("CSRF not presented")
	ErrCSRFNotPresented        = errors.New("CSRF not presented")
	NotRequiredFieldsError     = errors.New("No such required fields")
	ErrNotRequiredFields       = errors.New("No such required fields")
	BadQueryParamsError        = errors.New("Invalid query params")
	ErrBadQueryParams          = errors.New("Invalid query params")
	InternalServerError        = errors.New("Internal Server Erroror")
	ErrInternalServer          = errors.New("Internal Server Erroror")
	RequestTimeoutError        = errors.New("Request Timeout")
	ErrRequestTimeout          = errors.New("Request Timeout")
	ExistsEmailError           = errors.New("User with given email already exists")
	ErrExistsEmail             = errors.New("User with given email already exists")
	InvalidJWTTokenError       = errors.New("Invalid JWT token")
	ErrInvalidJWTToken         = errors.New("Invalid JWT token")
	InvalidJWTClaimsError      = errors.New("Invalid JWT claims")
	ErrInvalidJWTClaims        = errors.New("Invalid JWT claims")
	NotAllowedImageHeaderError = errors.New("Not allowed image header")
	ErrNotAllowedImageHeader   = errors.New("Not allowed image header")
	OTPCodeError               = errors.New("OTP code Erroror")
	ErrOTPCodeE                = errors.New("OTP code Error")
)
