DROP TABLE IF EXISTS users                CASCADE;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";


CREATE TABLE IF NOT EXISTS users (
   id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
   account VARCHAR (50) NOT NULL,
   email VARCHAR (255) UNIQUE NOT NULL,
   password VARCHAR (255) NOT NULL,
   status bool NOT NULL DEFAULT FALSE,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
